---by Walter White
--Des nouvelles donnees seront ajouté prochainement
--Je release des la liste agrandie

Citizen.CreateThread(function()
--load unloaded ipl's
  LoadMpDlcMaps()
  EnableMpDlcMaps(true)
  RequestIpl("FIBlobbyfake")
  RequestIpl("DT1_03_Gr_Closed")
  RequestIpl("v_tunnel_hole")
  RequestIpl("TrevorsMP")
  RequestIpl("TrevorsTrailer")
  RequestIpl("farm")
  RequestIpl("farmint")
  RequestIpl("farmint_cap")
  RequestIpl("farm_props")
  RequestIpl("CS1_02_cf_offmission")
  --IPL Appartements
  RequestIpl("apa_v_mp_h_01_a")
  RequestIpl("apa_v_mp_h_01_c")
  RequestIpl("apa_v_mp_h_01_b")
  RequestIpl("apa_v_mp_h_02_a")
  RequestIpl("apa_v_mp_h_02_c")
  RequestIpl("apa_v_mp_h_02_b")
  RequestIpl("apa_v_mp_h_03_a")
  RequestIpl("apa_v_mp_h_03_c")
  RequestIpl("apa_v_mp_h_03_b")
  RequestIpl("apa_v_mp_h_04_a")
  RequestIpl("apa_v_mp_h_04_c")
  RequestIpl("apa_v_mp_h_04_b")
  RequestIpl("apa_v_mp_h_05_a")
  RequestIpl("apa_v_mp_h_05_c")
  RequestIpl("apa_v_mp_h_05_b")
  RequestIpl("apa_v_mp_h_06_a")
  RequestIpl("apa_v_mp_h_06_c")
  RequestIpl("apa_v_mp_h_06_b")
  RequestIpl("apa_v_mp_h_07_a")
  RequestIpl("apa_v_mp_h_07_c")
  RequestIpl("apa_v_mp_h_07_b")
  RequestIpl("apa_v_mp_h_08_a")
  RequestIpl("apa_v_mp_h_08_c")
  RequestIpl("apa_v_mp_h_08_b")
  --Arcadius Buisness Centre
  RequestIpl("ex_dt1_02_office_02b")
  RequestIpl("ex_dt1_02_office_02c")
  RequestIpl("ex_dt1_02_office_02a")
  RequestIpl("ex_dt1_02_office_01a")
  RequestIpl("ex_dt1_02_office_01b")
  RequestIpl("ex_dt1_02_office_01c")
  RequestIpl("ex_dt1_02_office_03a")
  RequestIpl("ex_dt1_02_office_03b")
  RequestIpl("ex_dt1_02_office_03c")
  --Maze Bank Building
  RequestIpl("ex_dt1_11_office_02b")
  RequestIpl("ex_dt1_11_office_02c")
  RequestIpl("ex_dt1_11_office_02a")
  RequestIpl("ex_dt1_11_office_01a")
  RequestIpl("ex_dt1_11_office_01b")
  RequestIpl("ex_dt1_11_office_01c")
  RequestIpl("ex_dt1_11_office_03a")
  RequestIpl("ex_dt1_11_office_03b")
  RequestIpl("ex_dt1_11_office_03c")
  --Lom Bank
  RequestIpl("ex_sm_13_office_02b")
  RequestIpl("ex_sm_13_office_02c")
  RequestIpl("ex_sm_13_office_02a")
  RequestIpl("ex_sm_13_office_01a")
  RequestIpl("ex_sm_13_office_01b")
  RequestIpl("ex_sm_13_office_01c")
  RequestIpl("ex_sm_13_office_03a")
  RequestIpl("ex_sm_13_office_03b")
  RequestIpl("ex_sm_13_office_03c")
  --Maze Bank West
  RequestIpl("ex_sm_15_office_02b")
  RequestIpl("ex_sm_15_office_02c")
  RequestIpl("ex_sm_15_office_02a")
  RequestIpl("ex_sm_15_office_01a")
  RequestIpl("ex_sm_15_office_01b")
  RequestIpl("ex_sm_15_office_01c")
  RequestIpl("ex_sm_15_office_03a")
  RequestIpl("ex_sm_15_office_03b")
  RequestIpl("ex_sm_15_office_03c")
  --Clubhouse & Warehouses
  RequestIpl("bkr_biker_interior_placement_interior_0_biker_dlc_int_01_milo")
  RequestIpl("bkr_biker_interior_placement_interior_1_biker_dlc_int_02_milo")
  RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware01_milo")
  RequestIpl("bkr_biker_interior_placement_interior_3_biker_dlc_int_ware02_milo")
  RequestIpl("bkr_biker_interior_placement_interior_4_biker_dlc_int_ware03_milo")
  RequestIpl("bkr_biker_interior_placement_interior_5_biker_dlc_int_ware04_milo")
  RequestIpl("bkr_biker_interior_placement_interior_6_biker_dlc_int_ware05_milo")
  RequestIpl("ex_exec_warehouse_placement_interior_1_int_warehouse_s_dlc_milo")
  RequestIpl("ex_exec_warehouse_placement_interior_0_int_warehouse_m_dlc_milo")
  RequestIpl("ex_exec_warehouse_placement_interior_2_int_warehouse_l_dlc_milo")
  RequestIpl("imp_impexp_interior_placement_interior_1_impexp_intwaremed_milo_")
  --Special Locations
  RequestIpl("cargoship")
  RequestIpl("SUNK_SHIP_FIRE")
  RequestIpl("sunkcargoship")
  RequestIpl("redCarpet")
  RequestIpl("DES_StiltHouse_imapend")
  RequestIpl("DES_stilthouse_rebuild")
  RequestIpl("FINBANK")
  RequestIpl("TrevorsMP")
  RequestIpl("TrevorsTrailerTidy")
  RequestIpl("SP1_10_real_interior")
  RequestIpl("refit_unload")
  RequestIpl("post_hiest_unload")
  RequestIpl("FIBlobby")
  -------Special Locations (Multiple IPL per location)------------
  --Dignity Heist Yacht
  RequestIpl("smboat")
  RequestIpl("smboat_lod")
  RequestIpl("hei_yacht_heist")
  RequestIpl("hei_yacht_heist_enginrm")
  RequestIpl("hei_yacht_heist_Lounge")
  RequestIpl("hei_yacht_heist_Bridge")
  RequestIpl("hei_yacht_heist_Bar")
  RequestIpl("hei_yacht_heist_Bedrm")
  RequestIpl("hei_yacht_heist_DistantLights")
  RequestIpl("hei_yacht_heist_LODLights")
  --Dignity Party Yacht
  RequestIpl("smboat")
  RequestIpl("smboat_lod")
  RequestIpl("hei_yacht_heist")
  RequestIpl("hei_yacht_heist_enginrm")
  RequestIpl("hei_yacht_heist_Lounge")
  RequestIpl("hei_yacht_heist_Bridge")
  RequestIpl("hei_yacht_heist_Bar")
  RequestIpl("hei_yacht_heist_Bedrm")
  RequestIpl("hei_yacht_heist_DistantLights")
  RequestIpl("hei_yacht_heist_LODLights")
  --Aircraft Carrier
  RequestIpl("hei_carrier")
  RequestIpl("hei_carrier_DistantLights")
  RequestIpl("hei_Carrier_int1")
  RequestIpl("hei_Carrier_int2")
  RequestIpl("hei_Carrier_int3")
  RequestIpl("hei_Carrier_int4")
  RequestIpl("hei_Carrier_int5")
  RequestIpl("hei_Carrier_int6")
  RequestIpl("hei_carrier_LODLights")
  --Bridge Train Crash
  RequestIpl("canyonriver01_traincrash")
  RequestIpl("railing_end")
  --Bridge Train Normal
  RequestIpl("canyonriver01")
  RequestIpl("railing_start")
  --ONeils Farm Burnt
  RequestIpl("farmint")
  RequestIpl("farm_burnt")
  RequestIpl("farm_burnt_props")
  RequestIpl("des_farmhs_endimap")
  RequestIpl("des_farmhs_end_occl")
  --ONeils Farm
  RequestIpl("farm")
  RequestIpl("farm_props")
  RequestIpl("farm_int")
  --Bunker
  RequestIpl("gr_entrance_placement")
  RequestIpl("gr_grdlc_interior_placement")
  RequestIpl("gr_grdlc_interior_placement_interior_0_grdlc_int_01_milo_")
  RequestIpl("gr_grdlc_interior_placement_interior_1_grdlc_int_02_milo_")
  RequestIpl("gr_case0_bunkerclosed")
  RequestIpl("gr_case1_bunkerclosed")
  RequestIpl("gr_case2_bunkerclosed")
  RequestIpl("gr_case3_bunkerclosed")
  RequestIpl("gr_case4_bunkerclosed")
  RequestIpl("gr_case5_bunkerclosed")
  RequestIpl("gr_case6_bunkerclosed")
  RequestIpl("gr_case7_bunkerclosed")
  RequestIpl("gr_case9_bunkerclosed")
  RequestIpl("gr_case10_bunkerclosed")
  RequestIpl("gr_case11_bunkerclosed")  
  --Morgue
  RequestIpl("coronertrash")
  RequestIpl("Coroner_Int_On")
  -------END----- 
  
end)
